DI-22 - additional work - increase retries for validator & add to command line.
DataBiosphere/hca-import-validation pull request #20
Opened 2022-07-28 18:25 UTC by bahill

2022-07-28 18:27 UTC, bahill commented
NB - if you look at the actions, you'll see that the linter is failing to set up. I ran this through pylint via my IDE and cleaned up all errors. I left suggestions alone like missing docstrings. 
I don't know if you want to block the release of this update into the ingest pipeline until we get the repo updated to allow super-linter...etc.

2022-07-29 17:32 UTC, danielsotirhos requested changes

2022-07-29 17:32 UTC, danielsotirhos commented on hca/staging_area_validator.py
> +        self.total_retries = total_retries
To match the existing code there should be a blank line before this and no blank line after.

2022-07-29 17:32 UTC, danielsotirhos commented on hca/staging_area_validator.py
> +        """
The docstring doesn't add much, and `validator` is a cached property, not a function.

2022-07-29 17:32 UTC, danielsotirhos commented on hca/staging_area_validator.py
> +        # for next round of dev - metadata_type variable is not used (according to pylint)
```suggestion
        # TODO: remove unused `metadata_type`
```

2022-07-29 17:32 UTC, danielsotirhos commented on hca/staging_area_validator.py
> +    ) -> None:
```suggestion
    def validate_json(cls,
                       file_json: JSON,
                       total_retries: int,
                       schema: Optional[JSON] = None
                       ) -> None:
```
The `file_json` parameter makes more sense as the first parameter to `validate_json`

2022-07-29 17:32 UTC, danielsotirhos commented on hca/staging_area_validator.py
> +                schema = cls._download_schema(total_retries, file_json["describedBy"])
```suggestion
                schema = cls._download_schema(file_json["describedBy"], total_retries)
```

2022-07-29 17:32 UTC, danielsotirhos commented on hca/staging_area_validator.py
> +    def _download_schema(cls, total_retries, schema_url: str) -> JSON:
```suggestion
    def _download_schema(cls, schema_url: str, total_retries: int) -> JSON:
```

2022-07-29 17:32 UTC, danielsotirhos commented on hca/staging_area_validator.py
> +        print("total_retries = " + str(total_retries))
```suggestion
        print(f"Total_retries = {total_retries}")
```

2022-07-29 17:32 UTC, danielsotirhos commented on validate_staging_area.py
> +        "Syntax is gs://<bucket>[/<path>].",
```suggestion
        help="The Google Cloud Storage URL of the staging area. "
             "Syntax is gs://<bucket>[/<path>].",
```

2022-07-29 17:32 UTC, danielsotirhos commented on validate_staging_area.py
> +        "in the staging area for input-only entities.",
```suggestion
        help="Ignore errors caused by metadata files not found "
             "in the staging area for input-only entities.",
```

2022-07-29 17:32 UTC, danielsotirhos commented on validate_staging_area.py
> +        help="The number of times to retry the validation process.",
```suggestion
        help="The number of times to retry the validation process. "
             "The default is '10'.",
```

2022-07-29 23:13 UTC, danielsotirhos requested changes
Sorry for not thinking of these on the first pass.

2022-07-29 23:13 UTC, danielsotirhos commented on validate_staging_area.py
> +        "-t",
```suggestion
        "--max-retries",
        "-r",
```

2022-07-29 23:13 UTC, danielsotirhos commented on validate_staging_area.py
> +        dest="total_retries",
```suggestion
        dest="max_retries",
```


..and rename every `total_retries` variable / parameter to `max_retries`

2022-07-29 23:13 UTC, danielsotirhos commented on hca/staging_area_validator.py
> +        print(f"total_retries = {total_retries}")
This causes noisy output (`total_retries = 10` printed before every  file validated). Consider changing the `print` to a `log.debug`, or simply removing it.

2022-08-01 13:16 UTC, aherbst-broad approved these changes
Making the param configurable looks good.

2022-08-03 17:02 UTC, danielsotirhos approved these changes
Approved.

2022-08-04 16:48 UTC, merged